apiVersion: apps/v1
kind: Deployment
metadata:
  name: spring-kube-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: spring-kube
  template:
    metadata:
      labels:
        app: spring-kube
    spec:
      containers:
        - name: spring-kube
          image: sinugaud/spring-kube:latest
          ports:
            - containerPort: 8080 # Ensure this port matches your application's port
---
apiVersion: v1
kind: Service
metadata:
  name: spring-kube-service
spec:
  selector:
    app: spring-kube
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080 # Ensure this port matches your containerPort in Deployment
  type: LoadBalancer # Change to NodePort or ClusterIP as needed
